language: generic 
sudo: required
services: 
    - docker
    
before_install:
    - docker build -t nextt-test/docker-react -f Dockerfile.dev .
    
script:
  - docker run -e CI=true nextt-test/docker-react npm run test